server:
 port: 9000

spring:
 application:
  name: Api-Gateway
 cloud:
  gateway:
   routes:
    - id: user-ms
      uri: lb://user-ms
      predicates:
      - Path=/user/**
    - id: contacts-ms
      uri: lb://contacts-ms
      predicates:
      - Path=/contacts/**

eureka:
  instance:
   hostname: localhost

  client:
   service-url:
     defaultZone: http://localhost:8761/eureka