resilience4j.circuitbreaker:
   instances:
    userService:
      failureRateThreshold: 50
      slidingWindowSize: 5
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 20s
      automaticTransitionFromOpenToHalfOpenEnabled: true

management:
 health:
  circuitbreakers:
    enabled: true
 endpoints:
  web:
    exposure:
      include: '*'